# GoReleaser configuration for ss-plugin-degit
# Documentation: https://goreleaser.com
#
# IMPORTANT: Archive naming convention MUST match ss-cli expectations:
# - Format: {repo}-{os}-{arch}.tar.gz (e.g., ss-plugin-degit-linux-amd64.tar.gz)
# - OS: lowercase (linux, darwin, windows)
# - Arch: golang format (amd64, arm64)

version: 2

project_name: ss-plugin-degit

before:
  hooks:
    - go mod tidy
    # Generate plugin.yaml from template with version injection
    # Use sh -c to ensure shell processes the redirect properly
    - sh -c "sed 's/__VERSION__/{{ .Version }}/g' plugin.yaml.tpl > plugin.yaml"

builds:
  - id: ss-plugin-degit
    main: .
    binary: ss-plugin-degit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.CommitDate}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: ss-plugin-degit
    # Name template MUST match ss-cli's expected format:
    # {project}-{os}-{arch}.tar.gz (e.g., ss-plugin-degit-linux-amd64.tar.gz)
    # See: ss-cli/cmd/plugin.go:319-324
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*
      # plugin.yaml is generated from plugin.yaml.tpl in before.hooks
      - src: plugin.yaml
        dst: plugin.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: ssgohq
    name: ss-plugin-degit
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
  header: |
    ## ss-plugin-degit v{{ .Version }}

    Fast git repository scaffolding without history, with private GitHub repo support.
  footer: |
    ## Installation

    ```bash
    # Using ss-cli
    ss plugin install github.com/ssgohq/ss-plugin-degit

    # Or download the appropriate archive for your platform from the assets below
    ```

    **Full Changelog**: https://github.com/ssgohq/ss-plugin-degit/compare/{{ .PreviousTag }}...{{ .Tag }}
